name: Cypress Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  clean-cypress-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Force Install dependencies
        run: npm install --legacy-peer-deps || npm install --force
      - name: Run Cypress Tests
        run: npx cypress run